no_6/routes/admin.php
<?php


//

Route::get('/', function() {
    return view("admin.index");
})->name('admin.index');

Route::resource('/category', 'CategoryController');
Route::resource('/product', 'ProductController');
Route::get('/order', 'OrderController@list_order')->name('order.list_order');
Route::get('/order/{order}', 'OrderController@showlist_order')->name('order.showlist_order');

no_6/routes/web.php
 <?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
| 
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/','Frontend\\HomeController@index')->name('homepage');
Route::get('/product/{product}','Frontend\\ProductController@show')->name('frontend.product.show');

Route::get('/product/category/{category}','Frontend\\ProductController@byCategory')->name('frontend.product.bycategory');
Route::get('/cart/checkout', 'Frontend\\CheckoutController@index')->middleware('auth')->name('checkout.index');
Route::post('/cart/checkout', 'Frontend\\CheckoutController@store')->middleware('auth')->name('checkout.store');
Route::get('/cart/{product}', 'Frontend\\CartController@addItem')->middleware('auth')->name('cart.add.item');
Route::get('/cart', 'Frontend\\CartController@index')->middleware('auth')->name('cart.index');
Route::get('/order', 'Frontend\\OrderController@index')->middleware('auth')->name('order.index');

Route::get('/order/{order}', 'Frontend\\OrderController@show')->middleware('auth')->name('order.show');





Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/admin/login', function() {
    return view('admin.login');
});



 

no_6/app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name','slug','description'];


    public function getRouteKeyName()
    {
    	return 'slug';
    }
    public function products()
    {
    	return $this->belongsToMany(Product::class);
    }
}

no_6/app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;
use Illuminate\Support\Str;
class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('name','asc')->paginate();
        return view('admin.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'description' => 'required'
        ]);

        Category::create([
            'name'  => $request->name,
            'slug'  => str::slug($request->name),
            'description'=> $request->description

        ]);

        return redirect()->route('category.index')->with('success','Berhasil ditambahkan dengan category :' . $request->name);


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {

        $category->update([
            'name'  => $request->name,
            'slug'  => str::slug($request->name),
            'description'=> $request->description

        ]);

        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {

          $category->delete();
          return back()->with('danger','Berhasil dihapus');
    }
}

no_6/resources/views/admin/category/create.blade.php
@extends('admin.templates.default')
@section('content')
<section class="content-header">
	<h1>
	Category Product
	<small></small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li><i class="glyphicon glyphicon-info-sign"></i> Category</li>
		<li><a href="#"><i class="fa fa-files-o"></i> Category </a></li>
		<li class="active">Add Category Product</li>
	</ol>
</section>
<section class="content">
	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title">Add Category Product</h3>
		</div>
		<div class="box-body">
			<div class="form-group">
				<form  method="post" action="{{ route('category.store') }}">
					@csrf
					<div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
						<label for="name" class="col-md-2 control-label">Name</label>
						<div class="col-md-4">
							<input type="text" name="name" placeholder="Name product" class="form-control">
							{!! $errors->first('name', '<p class="help-block">:message</p>') !!}
						</div>
					</div>
					<br>
					<br>
					<br>
					<br>
					<div class="form-group {{ $errors->has('description') ? ' has-error' : '' }}">
						<label for="slug" class="col-md-2 control-label">Description</label>
						<div class="col-md-4">
							<textarea name="description" rows="2" placeholder="Description" class="form-control"></textarea>
							{!! $errors->first('description', '<p class="help-block">:message</p>') !!}
						</div>
					</div>
					<br>
					<br>
					<br>
					<br>
					<div class="box-footer">
						<div class="form-group">
							<div class="col-md-4 col-md-offset-2">
								<button type="submit" class="btn btn-primary">Save</button>
								<a class="btn btn-default" href="{{ route('category.index') }}"> Cancel </a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</section>
	@endsection

no_6/resources/views/admin/category/edit.blade.php
@extends('admin.templates.default')


@section('content')
<section class="content-header">
	<h1>
		Category Product
		<small></small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li><i class="glyphicon glyphicon-info-sign"></i> Category</li>
		<li><a href="#"><i class="fa fa-files-o"></i> Category </a></li>
		<li class="active">Add Category Product</li>
	</ol>
</section>
<section class="content">
	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title">Add Category Product</h3>
		</div>
		<div class="box-body">
			<div class="form-group">
				<form  method="post" action="{{ route('category.update', $category->id) }}">
					@csrf
					@method('PUT')
					<div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
						<label for="name" class="col-md-2 control-label">Name</label>
						<div class="col-md-4">
							<input type="text" name="name" value="{{ $category->name }}"  placeholder="Name product" class="form-control">
							{!! $errors->first('name', '<p class="help-block">:message</p>') !!}
						</div>
					</div>
					<br>
					<br>
					<br>
					<br>
					<div class="form-group {{ $errors->has('description') ? ' has-error' : '' }}">
						<label for="slug" class="col-md-2 control-label">Description</label>
						<div class="col-md-4">
							<textarea name="description" rows="2" placeholder="Description" class="form-control">{{ $category->description }}</textarea>
							{!! $errors->first('description', '<p class="help-block">:message</p>') !!}
						</div>
					</div>
					<br>
					<br>
					<br>
					<br>
					<div class="box-footer">
						<div class="form-group">
							<div class="col-md-4 col-md-offset-2"> 
								<button type="submit" class="btn btn-primary">Update</button>
								<a class="btn btn-default" href="{{ route('category.index') }}"> Cancel </a> 
							</div>
						</div>
					</div>
				</form>
				</div>
			</div>
	</section>
	@endsection

no_6/resources/views/admin/category/index.blade.php
@extends('admin.templates.default')


@section('content')

  <section class="content-header">
    <h1>
      Category
      <small></small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{ url('/home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><i class="glyphicon glyphicon-info-sign"></i> Category</li>
      <li class="active"><i class="fa fa-files-o"></i> Daftar Category </li>
    </ol> 
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row" id="field_detail">
      <div class="col-md-12">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title"><b>Daftar Category Product</b></h3>
            <div class="box-tools pull-right">
              <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
              </button>
            </div>
            <hr>
            <a class="btn btn-primary" href="{{ route('category.create') }}">
              <span class="fa fa-plus"></span> Add Category
            </a>
          </div>
            @include('admin.templates.partials._alert')

          <!-- /.box-header -->
          <div class="box-body">         
         <table id="tblDetail" class="table table-striped table-condensed table-bordered" cellspacing="0" width="100%">
              <thead>
                <tr>
                  <th style='width: 1%;text-align: center'>No</th>
                  <th style='width: 5%;text-align: center'>Name</th>                
                  <th style='width: 5%;text-align: center'>Slug </th>
                  <th style='width: 10%;text-align: center'>Description</th>
                  <th style='width: 2%;text-align: center'>Action</th>
                </tr>
              </thead>
              <tbody>
               {{--  @php $no = 1; @endphp --}}
                @foreach($categories as $category)
                <tr>
                  <td>#</td>
                  <td>{{ $category->name }}</td>
                  <td>{{ $category->slug }}</td>
                  <td>{{ $category->description }}</td>
                  <td>
                    <a style="text-align: center" href="{{ route('category.edit', $category) }}" class="btn btn-sm btn-warning" title=""><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</a>
                   <button id="delete" data-title="{{ $category->name }}" href="{{ route('category.destroy', $category) }}" class="btn btn-sm btn-danger"><i class="fa fa-trash" aria-hidden="true"></i> Delete</button>
                  </td>
                  <form action="" method="post" value="" id="deleteForm">
                    @csrf
                    @method('DELETE')
                    <input type="submit" name="" style="display: none;">
                  </form>
                </tr>
                @endforeach
              </tbody>
            </table>      
          </div>
          <!-- /.box-body -->
          <div class="box-footer clearfix">
            {{ $categories->links('vendor.pagination.adminlte') }}
          </div>
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
  <!-- /.content -->
@endsection
@push('scripts')
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<script type="text/javascript">
  $('button#delete').on('click', function(){
    var href = $(this).attr('href');
    var title = $(this).data('title');

    swal({
      title: "Are you sure to delete this data "+ title +" category?",
      text: "Once deleted, you will not be able to recover this category!",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        document.getElementById('deleteForm').action = href;
        document.getElementById('deleteForm').submit();
        swal("Your category has been deleted!", {
          icon: "success",
        });
      } 
    });
  });
</script>
@endpush